### ISSUE TITLE
Non-Latin Artists and Tracks result in ` - .mp3` as an output filename

### ISSUE THREAD

**Issue by sturd** [LumePart/Explo#10]
I noticed the following line in my download log;

`2024/12/06 20:37:35 compiled command: ffmpeg -i /explo/ - _TEMP.mp3 -loglevel error -map 0:a -metadata artist=結束バンド -metadata title=カラカラ -metadata album=結束バンド /explo/ - .mp3`

This has resulted in the ` - .mp3` file being left in the downloads directory.  Should other suggestions be non-Latin, in this playlist, or future playlists, this file will be overwritten.

I would suggest either generating a GUID for this file or, if possible, ensuring the original artist/track are preserved.

Cheers.

**Comment by LumePart** [comment]
Thanks for reporting! This was a oversight on my part. 
It is now fixed [in the latest release](https://github.com/LumePart/Explo/releases/tag/v0.6.5). The artist and title will be preserved in file naming (e.g `ラカラ-結束バンド`)

**Comment by sturd** [comment]
Wow, thanks for the quick reply and fix.  Will pull the latest image and have a try with it - I have to re-generate the playlist again anyway as I exhausted my Youtube API quota, poking and prodding the container. :)
