### ISSUE TITLE
Consider Jellyfin support

### ISSUE THREAD

**Issue by amarevite** [LumePart/Explo#3]
[Possible Jellyfin support was mentioned on Reddit](https://www.reddit.com/r/selfhosted/comments/1eeet7g/-/lfg6mxl). I'm opening this issue so support/progress can be tracked in the project's repo.

**Comment by LumePart** [comment]
Began looking into this. Stumbled upon an (minor) issue.
As of right now, when deleting the music file from the server, it will persist in jellyfin until it is manually deleted. Same goes for Albums and Artists ([issue in Jellyfin repo](https://github.com/jellyfin/jellyfin/issues/9259)).
To avoid this and keep things clean, I think it would be beneficial to create a separate media library for Explo. This way, it wouldn't "pollute" the main music library with potentially messy metadata.
Development will be in the [dev branch](https://github.com/LumePart/Explo/tree/dev)

**Comment by LumePart** [comment]
Jellyfin support added in [v0.6.0](https://github.com/LumePart/Explo/releases/tag/v0.6.0)
A separate library will be created for Explo
