### ISSUE TITLE
Consider a Docker Image

### ISSUE THREAD

**Issue by amarevite** [LumePart/Explo#5]
Consider implementing a `Dockerfile` and `docker-compose.yml` so that Explo can be run via Docker. GitHub Actions can build the image so it can be pulled from this repo without each person having to build it locally themselves. [Here's an example](https://github.com/amarevite/docker-caddy-personal/blob/7291431ea03d98dc7f5ca2a77cc7f4053acb5c73/.github/workflows/check-update.yml#L35) of a GitHub Actions workflow to build a Docker image. [This link](https://docs.docker.com/build/building/multi-stage/) has info about multi-stage Docker image builds with an example for a basic Go project.

**Comment by NovaCyntax** [comment]
Seconding this. I will deploy it once there's a docker image, I try to avoid running things that don't have images to make management easier.

**Comment by marcus-k** [comment]
Definitely, I would consider much more with docker containers for easier testing.

**Comment by zodac** [comment]
Yup, I'm not likely to add binaries to my system for individual programs, but a docker image would be fantastic.

**Comment by LumePart** [comment]
Thanks @amarevite, @demiGod095 for the guides and examples. I've added a [docker package](https://github.com/LumePart/Explo/pkgs/container/explo) in the latest dev version. Also added a [docker-compose](https://github.com/LumePart/Explo/blob/dev/docker-compose.yaml).

Live package will hopefully come soon, once I add some more QoL improvements.
Keeping this open until then

**Comment by layanto** [comment]
What does $DOWNLOAD_DIR mean in the docker compose file?
