### ISSUE TITLE
Cant seem to get it to wrok with navidrome

### ISSUE THREAD

**Issue by demiGod095** [LumePart/Explo#6]
I have added all the required flags to local.env

When I run the binary, I get:
```
2024/10/23 23:02:16 using subsonic
2024/10/23 23:02:17 failed to unmarshal body: unexpected end of JSON input
```

Is there a way to enable debugging to check what is going on ?

**Comment by LumePart** [comment]
There's currently no way to enable debugging, will try to add it ASAP

**Comment by LumePart** [comment]
I’ve added preliminary debugging in the latest release: [v0.6.1](https://github.com/LumePart/Explo/releases/tag/v0.6.1). The debugging right now logs all failed unmarshal operations.
Hopefully this gives more context

**Comment by realthing-shreyas** [comment]
Thanks @LumePart,
I can see now, I am getting an empty response.

Here's my redacted local.env for ref (in case I am doing something wrong)

```
DEBUG=true
# Music system you use (jellyfin, mpd or subsonic)
EXPLO_SYSTEM=subsonic
# Address of music system (required for subsonic, jellyfin)
SYSTEM_URL="https://navidrome.example.com"
# User which has admin access to the music server (required for subsonic)
SYSTEM_USERNAME=admin
# Password for the user (required for subsonic)
SYSTEM_PASSWORD="password which has spaces in it"
# API Key from music server (required for jellyfin)
#API_KEY=
# Directory where to download tracks (required)
DOWNLOAD_DIR=/mnt/
# Username for ListenBrain recommendations (required)
LISTENBRAINZ_USER=d********5
# Youtube Data API key (required)
YOUTUBE_API_KEY=A*************************************s

## Misc:

# Assign custom path to the ffmpeg binary
# FFMPEG_PATH=
# Define a custom filename sepatator for special characters
# FILENAME_SEPARATOR=
# true to keep pervious weeks discoveries, only set to false if the parent folder only contains discovered songs (deletes every file in folder)
PERSIST=true
# 'playlist' to get tracks from Weekly Exploration playlist, anything else gets it from API (not the best recommendations). 'test' will download 1 song
LISTENBRAINZ_DISCOVERY=test
# Time to sleep (in minutes) between scanning and querying tracks from your system (If using Subsonic, Jellyfin)
SLEEP=1
```

**Comment by LumePart** [comment]
It seems like ListenBrainz sends an empty response from the recommendations API. 
Is your ListenBrainz account new?
Have you scrobbled something to ListenBrainz? (within the month or so)
I can't say for certain, but if you have a new account, it's likely that LB doesn't have enough data to generate recommendations to you

**Comment by demiGod095** [comment]
@LumePart, you are correct.
I ran the binary today and it worked!
Ill edit the subject for others who might see it later.

Thanks.
