### ISSUE TITLE
After downloading and converting the file from Listenbrainz to a .mp3, it doesnt seem to delete the .webm file it downloads

### ISSUE THREAD

**Issue by corylowry12** [LumePart/Explo#8]

**Comment by LumePart** [comment]
Hey, could you provide some more info, such as:

What operating system are you running?
Are you running docker or the binary?
Does it fail to delete every .webm file or just a few?

If you're running docker can you provide a output of `docker logs explo`?

**Comment by corylowry12** [comment]
Been trying to test this for you, but havent actually gotten it to finish downloading a whole playlist. Keeps giving me a 403 error when trying to find songs.

**Comment by LumePart** [comment]
I assume this is for Youtube.

This can happen for 3 reasons:
1. Your Youtube API Key is wrong.
2. If you make too many requests in a short period of time, Youtube can rate-limit you.
3. You have no Youtube API credits left (you can make 100 total requests per day).


Test your API key validity run this CURL command command:
 ``curl "https://youtube.googleapis.com/youtube/v3/search?part=snippet&q=test&type=video&videoCategoryId=10&key=YOUR_API_KEY"``
Don't forget to replace `YOUR_API_KEY` with your actual key, if you get a json response you should be good

Explo already makes 50 requests (by default) in a short period of time, if you have other tools that also access Youtube, you could get rate-limited. You can check your API usage in the [Google Cloud admin page](https://console.cloud.google.com/iam-admin/quotas?)

**Comment by LumePart** [comment]
Also [in the newest version](https://github.com/LumePart/Explo/releases/tag/v0.6.3) the .webm file will get deleted right after ffmpeg converts it to .mp3 (previously it deleted extra files if all songs had been downloaded)

**Comment by corylowry12** [comment]
hmm, that seems to be working. haven't been able to get it to add the virtual playlist to emby though. does it support emby?

**Comment by LumePart** [comment]
Unfortunately Explo doesn't support Emby yet, but if I have the time I'll for sure add support for it
